/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters
// ignore_for_file: invalid_use_of_internal_member

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _ida;
import 'package:http/http.dart' as _i85jenna;
import 'package:promise_client/src/protocol/friends/friendship.dart'
    as _i06n1i47;
import 'package:promise_client/src/protocol/friends/user_search_profile.dart'
    as _ihsmdl90;
import 'package:promise_client/src/protocol/greetings/greeting.dart'
    as _izk3ljs4;
import 'package:promise_client/src/protocol/promises/promise.dart' as _izrd4uei;
import 'package:promise_client/src/protocol/promises/promise_activity.dart'
    as _irwpjxuh;
import 'package:serverpod_auth_core_client/serverpod_auth_core_client.dart'
    as _iacc;
import 'package:serverpod_auth_idp_client/serverpod_auth_idp_client.dart'
    as _iaic;
import 'package:serverpod_client/serverpod_client.dart' as _isc;
import 'protocol.dart' as _il2as5qe;

/// By extending [RefreshJwtTokensEndpoint], the JWT token refresh endpoint
/// is made available on the server and enables automatic token refresh on the client.
/// {@category Endpoint}
class EndpointJwtRefresh extends _iacc.EndpointRefreshJwtTokens {
  EndpointJwtRefresh(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'jwtRefresh';

  /// Creates a new token pair for the given [refreshToken].
  ///
  /// If [refreshToken] is omitted, cookie-mode web clients fall back to the
  /// configured HttpOnly refresh cookie. When neither source is present this
  /// throws [RefreshTokenNotFoundException], the same public "no usable refresh
  /// credential" exception used for unknown refresh tokens.
  ///
  /// Can throw the following exceptions:
  /// -[RefreshTokenMalformedException]: refresh token is malformed and could
  ///   not be parsed. Not expected to happen for tokens issued by the server.
  /// -[RefreshTokenNotFoundException]: refresh token is unknown to the server.
  ///   Either the token was deleted or generated by a different server.
  /// -[RefreshTokenExpiredException]: refresh token has expired. Will happen
  ///   only if it has not been used within configured `refreshTokenLifetime`.
  /// -[RefreshTokenInvalidSecretException]: refresh token is incorrect, meaning
  ///   it does not refer to the current secret refresh token. This indicates
  ///   either a malfunctioning client or a malicious attempt by someone who has
  ///   obtained the refresh token. In this case the underlying refresh token
  ///   will be deleted, and access to it will expire fully when the last access
  ///   token is elapsed.
  ///
  /// This endpoint is unauthenticated, meaning the client won't include any
  /// authentication information with the call.
  @override
  _ida.Future<_iacc.AuthSuccess> refreshAccessToken({String? refreshToken}) =>
      caller.callServerEndpoint<_iacc.AuthSuccess>(
        'jwtRefresh',
        'refreshAccessToken',
        {'refreshToken': refreshToken},
        authenticated: false,
      );
}

/// {@category Endpoint}
class EndpointEmailIdp extends _iaic.EndpointEmailIdpBase {
  EndpointEmailIdp(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'emailIdp';

  @override
  _ida.Future<_isc.UuidValue> startRegistration({required String email}) =>
      caller.callServerEndpoint<_isc.UuidValue>(
        'emailIdp',
        'startRegistration',
        {'email': email},
      );

  @override
  _ida.Future<_iacc.AuthSuccess> login({
    required String email,
    required String password,
  }) => caller.callServerEndpoint<_iacc.AuthSuccess>(
    'emailIdp',
    'login',
    {
      'email': email,
      'password': password,
    },
  );

  @override
  _ida.Future<_isc.UuidValue> startPasswordReset({required String email}) =>
      caller.callServerEndpoint<_isc.UuidValue>(
        'emailIdp',
        'startPasswordReset',
        {'email': email},
      );

  /// Verifies an account request code and returns a token
  /// that can be used to complete the account creation.
  ///
  /// Throws an [EmailAccountRequestException] in case of errors, with reason:
  /// - [EmailAccountRequestExceptionReason.expired] if the account request has
  ///   already expired.
  /// - [EmailAccountRequestExceptionReason.policyViolation] if the password
  ///   does not comply with the password policy.
  /// - [EmailAccountRequestExceptionReason.invalid] if no request exists
  ///   for the given [accountRequestId] or [verificationCode] is invalid.
  @override
  _ida.Future<String> verifyRegistrationCode({
    required _isc.UuidValue accountRequestId,
    required String verificationCode,
  }) => caller.callServerEndpoint<String>(
    'emailIdp',
    'verifyRegistrationCode',
    {
      'accountRequestId': accountRequestId,
      'verificationCode': verificationCode,
    },
  );

  /// Completes a new account registration, creating a new auth user with a
  /// profile and attaching the given email account to it.
  ///
  /// Throws an [EmailAccountRequestException] in case of errors, with reason:
  /// - [EmailAccountRequestExceptionReason.expired] if the account request has
  ///   already expired.
  /// - [EmailAccountRequestExceptionReason.policyViolation] if the password
  ///   does not comply with the password policy.
  /// - [EmailAccountRequestExceptionReason.invalid] if the [registrationToken]
  ///   is invalid.
  ///
  /// Throws an [AuthUserBlockedException] if the auth user is blocked.
  ///
  /// Returns a session for the newly created user.
  @override
  _ida.Future<_iacc.AuthSuccess> finishRegistration({
    required String registrationToken,
    required String password,
  }) => caller.callServerEndpoint<_iacc.AuthSuccess>(
    'emailIdp',
    'finishRegistration',
    {
      'registrationToken': registrationToken,
      'password': password,
    },
  );

  /// Verifies a password reset code and returns a finishPasswordResetToken
  /// that can be used to finish the password reset.
  ///
  /// Throws an [EmailAccountPasswordResetException] in case of errors, with reason:
  /// - [EmailAccountPasswordResetExceptionReason.expired] if the password reset
  ///   request has already expired.
  /// - [EmailAccountPasswordResetExceptionReason.tooManyAttempts] if the user has
  ///   made too many attempts trying to verify the password reset.
  /// - [EmailAccountPasswordResetExceptionReason.invalid] if no request exists
  ///   for the given [passwordResetRequestId] or [verificationCode] is invalid.
  ///
  /// If multiple steps are required to complete the password reset, this endpoint
  /// should be overridden to return credentials for the next step instead
  /// of the credentials for setting the password.
  @override
  _ida.Future<String> verifyPasswordResetCode({
    required _isc.UuidValue passwordResetRequestId,
    required String verificationCode,
  }) => caller.callServerEndpoint<String>(
    'emailIdp',
    'verifyPasswordResetCode',
    {
      'passwordResetRequestId': passwordResetRequestId,
      'verificationCode': verificationCode,
    },
  );

  /// Completes a password reset request by setting a new password.
  ///
  /// The [verificationCode] returned from [verifyPasswordResetCode] is used to
  /// validate the password reset request.
  ///
  /// Throws an [EmailAccountPasswordResetException] in case of errors, with reason:
  /// - [EmailAccountPasswordResetExceptionReason.expired] if the password reset
  ///   request has already expired.
  /// - [EmailAccountPasswordResetExceptionReason.policyViolation] if the new
  ///   password does not comply with the password policy.
  /// - [EmailAccountPasswordResetExceptionReason.invalid] if no request exists
  ///   for the given [passwordResetRequestId] or [verificationCode] is invalid.
  ///
  /// Throws an [AuthUserBlockedException] if the auth user is blocked.
  @override
  _ida.Future<void> finishPasswordReset({
    required String finishPasswordResetToken,
    required String newPassword,
  }) => caller.callServerEndpoint<void>(
    'emailIdp',
    'finishPasswordReset',
    {
      'finishPasswordResetToken': finishPasswordResetToken,
      'newPassword': newPassword,
    },
  );

  @override
  _ida.Future<bool> hasAccount() => caller.callServerEndpoint<bool>(
    'emailIdp',
    'hasAccount',
    {},
  );
}

/// {@category Endpoint}
class EndpointFriend extends _isc.EndpointRef {
  EndpointFriend(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'friend';

  /// Searches for registered users by email or username, including friendship status with current user.
  _ida.Future<List<_ihsmdl90.UserSearchProfile>> searchUsers(String query) =>
      caller.callServerEndpoint<List<_ihsmdl90.UserSearchProfile>>(
        'friend',
        'searchUsers',
        {'query': query},
      );

  /// Sends a friend request to a target user ID.
  _ida.Future<_i06n1i47.Friendship> sendFriendRequest(String receiverUserId) =>
      caller.callServerEndpoint<_i06n1i47.Friendship>(
        'friend',
        'sendFriendRequest',
        {'receiverUserId': receiverUserId},
      );

  /// Retrieves pending friend requests sent TO the current authenticated user.
  _ida.Future<List<_ihsmdl90.UserSearchProfile>> getPendingFriendRequests() =>
      caller.callServerEndpoint<List<_ihsmdl90.UserSearchProfile>>(
        'friend',
        'getPendingFriendRequests',
        {},
      );

  /// Accepts an incoming friend request.
  _ida.Future<_i06n1i47.Friendship> acceptFriendRequest(int friendshipId) =>
      caller.callServerEndpoint<_i06n1i47.Friendship>(
        'friend',
        'acceptFriendRequest',
        {'friendshipId': friendshipId},
      );

  /// Rejects an incoming friend request.
  _ida.Future<_i06n1i47.Friendship> rejectFriendRequest(int friendshipId) =>
      caller.callServerEndpoint<_i06n1i47.Friendship>(
        'friend',
        'rejectFriendRequest',
        {'friendshipId': friendshipId},
      );

  /// Retrieves list of accepted friends for current authenticated user.
  _ida.Future<List<_ihsmdl90.UserSearchProfile>> getFriends() =>
      caller.callServerEndpoint<List<_ihsmdl90.UserSearchProfile>>(
        'friend',
        'getFriends',
        {},
      );

  /// Removes an accepted friend relationship.
  _ida.Future<void> removeFriend(String friendUserId) =>
      caller.callServerEndpoint<void>(
        'friend',
        'removeFriend',
        {'friendUserId': friendUserId},
      );
}

/// This is an example endpoint that returns a greeting message through
/// its [hello] method.
/// {@category Endpoint}
class EndpointGreeting extends _isc.EndpointRef {
  EndpointGreeting(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'greeting';

  /// Returns a personalized greeting message: "Hello {name}".
  _ida.Future<_izk3ljs4.Greeting> hello(String name) =>
      caller.callServerEndpoint<_izk3ljs4.Greeting>(
        'greeting',
        'hello',
        {'name': name},
      );
}

/// {@category Endpoint}
class EndpointPromise extends _isc.EndpointRef {
  EndpointPromise(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'promise';

  /// Creates a new promise for an accepted friend.
  _ida.Future<_izrd4uei.Promise> createPromise(_izrd4uei.Promise promise) =>
      caller.callServerEndpoint<_izrd4uei.Promise>(
        'promise',
        'createPromise',
        {'promise': promise},
      );

  /// Retrieves promises relevant to the current authenticated user.
  _ida.Future<List<_izrd4uei.Promise>> getPromises() =>
      caller.callServerEndpoint<List<_izrd4uei.Promise>>(
        'promise',
        'getPromises',
        {},
      );

  /// Retrieves a single promise by ID after authorizing participant access.
  _ida.Future<_izrd4uei.Promise?> getPromise(int id) =>
      caller.callServerEndpoint<_izrd4uei.Promise?>(
        'promise',
        'getPromise',
        {'id': id},
      );

  /// Retrieves activities for a promise after authorizing participant access.
  _ida.Future<List<_irwpjxuh.PromiseActivity>> getActivities(int promiseId) =>
      caller.callServerEndpoint<List<_irwpjxuh.PromiseActivity>>(
        'promise',
        'getActivities',
        {'promiseId': promiseId},
      );

  /// Adds a new activity update for a promise. Does NOT alter overall promise status.
  _ida.Future<_irwpjxuh.PromiseActivity> addActivity(
    int promiseId,
    String type,
    String message, {
    String? activityStatus,
  }) => caller.callServerEndpoint<_irwpjxuh.PromiseActivity>(
    'promise',
    'addActivity',
    {
      'promiseId': promiseId,
      'type': type,
      'message': message,
      'activityStatus': activityStatus,
    },
  );

  /// Confirms promise completion. Role is derived from authenticated user identity.
  _ida.Future<_izrd4uei.Promise> confirmPromiseCompletion(
    int promiseId,
    String role,
  ) => caller.callServerEndpoint<_izrd4uei.Promise>(
    'promise',
    'confirmPromiseCompletion',
    {
      'promiseId': promiseId,
      'role': role,
    },
  );

  /// Requests changes for a promise. Role is derived from authenticated user identity.
  _ida.Future<_izrd4uei.Promise> requestChanges(
    int promiseId,
    String role,
    String reason,
  ) => caller.callServerEndpoint<_izrd4uei.Promise>(
    'promise',
    'requestChanges',
    {
      'promiseId': promiseId,
      'role': role,
      'reason': reason,
    },
  );

  /// Explicitly updates the overall status of a promise.
  _ida.Future<_izrd4uei.Promise> updatePromiseStatus(
    int promiseId,
    String newStatus,
  ) => caller.callServerEndpoint<_izrd4uei.Promise>(
    'promise',
    'updatePromiseStatus',
    {
      'promiseId': promiseId,
      'newStatus': newStatus,
    },
  );
}

class Modules {
  Modules(Client client) {
    serverpod_auth_idp = _iaic.Caller(client);
    serverpod_auth_core = _iacc.Caller(client);
  }

  late final _iaic.Caller serverpod_auth_idp;

  late final _iacc.Caller serverpod_auth_core;
}

class Client extends _isc.ServerpodClientShared {
  Client(
    String host, {
    dynamic securityContext,
    Duration? streamingConnectionTimeout,
    Duration? connectionTimeout,
    Function(
      _isc.MethodCallContext,
      Object,
      StackTrace,
    )?
    onFailedCall,
    Function(_isc.MethodCallContext)? onSucceededCall,
    bool? disconnectStreamsOnLostInternetConnection,
    _i85jenna.Client? httpClientOverride,
  }) : super(
         host,
         _il2as5qe.Protocol(),
         securityContext: securityContext,
         streamingConnectionTimeout: streamingConnectionTimeout,
         connectionTimeout: connectionTimeout,
         onFailedCall: onFailedCall,
         onSucceededCall: onSucceededCall,
         disconnectStreamsOnLostInternetConnection:
             disconnectStreamsOnLostInternetConnection,
         httpClientOverride: httpClientOverride,
       ) {
    jwtRefresh = EndpointJwtRefresh(this);
    emailIdp = EndpointEmailIdp(this);
    friend = EndpointFriend(this);
    greeting = EndpointGreeting(this);
    promise = EndpointPromise(this);
    modules = Modules(this);
  }

  late final EndpointJwtRefresh jwtRefresh;

  late final EndpointEmailIdp emailIdp;

  late final EndpointFriend friend;

  late final EndpointGreeting greeting;

  late final EndpointPromise promise;

  late final Modules modules;

  @override
  Map<String, _isc.EndpointRef> get endpointRefLookup => {
    'jwtRefresh': jwtRefresh,
    'emailIdp': emailIdp,
    'friend': friend,
    'greeting': greeting,
    'promise': promise,
  };

  @override
  Map<String, _isc.ModuleEndpointCaller> get moduleLookup => {
    'serverpod_auth_idp': modules.serverpod_auth_idp,
    'serverpod_auth_core': modules.serverpod_auth_core,
  };
}
